name: Generate Changelog

on:
  workflow_dispatch:
  push:
    branches:
      - changelog

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository: 
          - cherrycl/edgex-go

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ matrix.repository }}

      - name: Get CommitId by Latest Stable Tag
        run: |
          git fetch --tags
          latest_stable=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1)
          latest_tag=$(git describe --tags --abbrev=0)

          next_stable=$(echo "$latest_tag" | sed -E 's/-dev.[0-9]+$//')
          next_version=$(echo "$next_stable" | sed -E 's/v//')
          
          echo "Generating changelog from $previous_tag to $latest_tag"
          commitId=$(git rev-list -n 1 ${{ env.LATEST_STABLE }})
          echo "commitId=$commitId" >> $GITHUB_ENV
          echo "NEXT_VERSION=$next_version" >> $GITHUB_ENV

      - name: Generate Changelogs
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: -- ${{ env.commitId }}..HEAD
        env:
          OUTPUT: CHANGELOG.md

      - name: Upload changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog-repo1
          path: CHANGELOG.md

